### ISSUE TITLE
create a aka.ms/playground for spring-cloud-playground

### ISSUE THREAD

**Issue by yaweiw** [Microsoft/spring-cloud-playground#109]
ideally have a FQDN for it.

**Comment by yaweiw** [comment]
@Matthew-Dong @sophiaso

**Comment by Matthew-Dong** [comment]
aka.ms/springplayground 

It's alive now. "playground" is already taken.

**Comment by Matthew-Dong** [comment]
aka.ms/springcloud

It's alive now. "playground" is already taken.
